---
- name: Testing initial on sobag
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: ubuntu
       image: "/v2/images/e493c376-a94f-48bd-a577-8f5e0f987b06/file"
       key_name: automation-key
       timeout: 200
       flavor: 865e07f67ed74039affb36b8a4513996
       auto_ip: no
       network: 68e81282-daff-4101-9135-0313c64b7132
       security_groups: default
       meta:
         os: ubuntu