---
- name: Testing initial on sobag
  hosts: localhost
  
  tasks:
  - name: Create a new instance and attaches to a network and passes metadata to the instance
    os_server:
       state: present
       name: ubuntu
       image: e493c376-a94f-48bd-a577-8f5e0f987b06
       key_name: automation-key
       timeout: 200
       flavor: 9b2dfaa6-766f-4d41-bee6-5c31b5792eac
       auto_ip: no
       network: 68e81282-daff-4101-9135-0313c64b7132
       security_groups: default
       meta:
         os: ubuntu